version: '2'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  dashing:
    image: frvi/dashing
    container_name: dashing
    hostname: dashing
    ports:
      - "3030:3030"
    volumes:
      - "./src/dashboards/prometheus.erb:/dashboards/prometheus.erb"
      - "./src/jobs/prometheus.rb:/jobs/prometheus.rb"
      - "./src/widgets/prometheus:/widgets/prometheus"
    links:
      - prometheus